version: '3.8'

services:
  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile.dev
    container_name: storage-dev
    env_file:
      - .env.dev
    volumes:
      - ./storage:/app:cached
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  pdf-service:
    build:
      context: ./pdf-generation-service
      dockerfile: Dockerfile.dev
    container_name: pdf-service-dev
    env_file:
      - .env.dev
    volumes:
      - ./pdf-generation-service:/app:cached
      - pdf_data:/app/wwwroot
    ports:
      - "5296:5296"
    command: dotnet watch run --urls http://0.0.0.0:5296

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    env_file:
      - .env.dev
    volumes:
      - ./frontend:/app:cached
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  media_data:
  static_data:
  pdf_data:
