version: '3.8'

services:
  # Django dev
  storage:
    build:
      context: .
      dockerfile: services/storage/Dockerfile.dev
    container_name: storage-dev
    env_file:
      - .env.dev
    volumes:
      - ./services/storage:/app:cached
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  # .NET dev with hot‑reload
  pdf-service:
    build:
      context: .
      dockerfile: services/pdf-generation-service/Dockerfile.dev
    container_name: pdf-service-dev
    env_file:
      - .env.dev
    volumes:
      - ./services/pdf-generation-service:/app:cached
      - pdf_data:/app/wwwroot
    ports:
      - "5296:5296"
    command: dotnet watch run --urls http://0.0.0.0:5296

  # React dev server
  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile.dev
    container_name: frontend-dev
    env_file:
      - .env.dev
    volumes:
      - ./services/frontend:/app:cached
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  media_data:
  static_data:
  pdf_data:
