# Generated by Django 5.2 on 2025-04-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_generatedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='units',
            field=models.CharField(choices=[('mm', 'Millimeters'), ('px', 'Pixels')], default='mm', max_length=5),
        ),
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('png', 'PNG Image'), ('svg', 'SVG Vector Image')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='bleeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneratedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generated_templates/')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_templates', to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='templates.page')),
            ],
            options={
                'unique_together': {('page', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='GeneratedPdf',
        ),
    ]
