# Generated by Django 4.2.8 on 2025-05-10 15:15

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.URLField(help_text='URL файла в хранилище')),
                ('size_bytes', models.PositiveIntegerField(help_text='Размер файла в байтах')),
                ('file_name', models.CharField(help_text='Имя файла', max_length=255)),
                ('content_type', models.CharField(help_text='MIME-тип файла', max_length=100)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('done', 'Завершено'), ('failed', 'Ошибка')], default='pending', help_text='Статус задачи', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Прогресс выполнения (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('error', models.TextField(blank=True, help_text='Сообщение об ошибке')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Время завершения', null=True)),
            ],
            options={
                'verbose_name': 'Задача рендеринга',
                'verbose_name_plural': 'Задачи рендеринга',
                'ordering': ['-started_at'],
            },
        ),
    ]
