# Generated by Django 4.2.8 on 2025-05-07 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(help_text='IP клиента')),
                ('data_input', models.JSONField(help_text='Сырые данные')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'В обработке'), ('done', 'Завершено'), ('failed', 'Ошибка')], default='pending', help_text='Статус', max_length=20)),
                ('worker_id', models.CharField(blank=True, help_text='Celery task id', max_length=255, null=True)),
                ('progress', models.IntegerField(default=0, help_text='% выполнения (0-100)')),
                ('error', models.TextField(blank=True, help_text='Сообщение об ошибке', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Когда началось')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Когда завершилось', null=True)),
                ('template_revision', models.ForeignKey(help_text='На основе какой версии', on_delete=django.db.models.deletion.CASCADE, related_name='render_tasks', to='templates.templaterevision')),
                ('user', models.ForeignKey(blank=True, help_text='Кто запросил', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача рендеринга',
                'verbose_name_plural': 'Задачи рендеринга',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.CharField(help_text='URL файла в Ceph', max_length=1000)),
                ('size_bytes', models.BigIntegerField(help_text='Размер')),
                ('file_name', models.CharField(help_text='Имя файла', max_length=255)),
                ('content_type', models.CharField(help_text='Content-Type', max_length=100)),
                ('task', models.ForeignKey(help_text='По какой задаче', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='generation.rendertask')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
