# Generated by Django 4.2.8 on 2025-05-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='template',
            field=models.ForeignKey(help_text='Шаблон, на основе которого рендерится документ', on_delete=django.db.models.deletion.CASCADE, related_name='render_tasks', to='templates.template'),
        ),
    ]
