# Generated by Django 4.2.8 on 2025-05-11 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, запросивший рендеринг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='task',
            field=models.ForeignKey(help_text='Задача рендеринга', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='generation.rendertask'),
        ),
        migrations.AddIndex(
            model_name='rendertask',
            index=models.Index(fields=['status', '-started_at'], name='generation__status_eb0282_idx'),
        ),
        migrations.AddIndex(
            model_name='rendertask',
            index=models.Index(fields=['user', '-started_at'], name='generation__user_id_a0c2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['task', '-created_at'], name='generation__task_id_19b07b_idx'),
        ),
    ]
