# Generated by Django 4.2.8 on 2025-05-09 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertask',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Кто запросил', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='task',
            field=models.ForeignKey(help_text='По какой задаче', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='generation.rendertask'),
        ),
    ]
