# Generated by Django 4.2.8 on 2025-05-11 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepermission',
            name='grantee',
            field=models.ForeignKey(blank=True, help_text='Кому выдано (NULL → публичная ссылка)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatepermission',
            name='template',
            field=models.ForeignKey(help_text='Шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='templates.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='format',
            field=models.ForeignKey(help_text='Формат шаблона', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='templates.format'),
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(help_text='Владелец шаблона', on_delete=django.db.models.deletion.CASCADE, related_name='owned_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='unit',
            field=models.ForeignKey(help_text='Единица измерения для шаблона', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='templates.unit'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='format_setting',
            field=models.ForeignKey(help_text='Какая настройка', on_delete=django.db.models.deletion.CASCADE, related_name='page_settings', to='templates.formatsetting'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='page',
            field=models.ForeignKey(help_text='Страница', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='templates.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(help_text='Родительский шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='templates.template'),
        ),
        migrations.AddField(
            model_name='formatsetting',
            name='format',
            field=models.ForeignKey(help_text='Для какого формата', on_delete=django.db.models.deletion.CASCADE, related_name='expected_settings', to='templates.format'),
        ),
        migrations.AddField(
            model_name='format',
            name='allowed_units',
            field=models.ManyToManyField(help_text='Разрешённые единицы измерения', related_name='formats', to='templates.unit'),
        ),
        migrations.AddField(
            model_name='fieldversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_versions', to='templates.template'),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='templates.field'),
        ),
        migrations.AddField(
            model_name='field',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates.page'),
        ),
        migrations.AddField(
            model_name='field',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates.template'),
        ),
        migrations.AddField(
            model_name='asset',
            name='page',
            field=models.ForeignKey(blank=True, help_text='NULL → глобальный ассет', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='templates.page'),
        ),
        migrations.AddField(
            model_name='asset',
            name='template',
            field=models.ForeignKey(help_text='Шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='templates.template'),
        ),
        migrations.AlterUniqueTogether(
            name='templatepermission',
            unique_together={('template', 'grantee')},
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['owner', '-created_at'], name='templates_t_owner_i_800e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_public', '-created_at'], name='templates_t_is_publ_4818bd_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['format', '-created_at'], name='templates_t_format__d4d443_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagesettings',
            unique_together={('page', 'format_setting')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('template', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='formatsetting',
            unique_together={('format', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldchoice',
            unique_together={('field', 'order'), ('field', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('template', 'page', 'key')},
        ),
    ]
