# Generated by Django 4.2.8 on 2025-05-09 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepermission',
            name='grantee',
            field=models.ForeignKey(blank=True, help_text='Кому выдано (NULL → публичная ссылка)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatepermission',
            name='template',
            field=models.ForeignKey(help_text='Шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='templates.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='format',
            field=models.ForeignKey(help_text='Формат шаблона', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='templates.format'),
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(help_text='Владелец шаблона', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='unit',
            field=models.ForeignKey(help_text='Единица измерения для шаблона', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='templates.unit'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='format_setting',
            field=models.ForeignKey(help_text='Какая настройка', on_delete=django.db.models.deletion.CASCADE, related_name='page_settings', to='templates.formatsetting'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='page',
            field=models.ForeignKey(help_text='Страница', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='templates.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(help_text='Родительский шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='templates.template'),
        ),
        migrations.AddField(
            model_name='formatsetting',
            name='format',
            field=models.ForeignKey(help_text='Для какого формата', on_delete=django.db.models.deletion.CASCADE, related_name='expected_settings', to='templates.format'),
        ),
        migrations.AddField(
            model_name='format',
            name='allowed_units',
            field=models.ManyToManyField(help_text='Разрешённые единицы измерения', related_name='formats', to='templates.unit'),
        ),
        migrations.AddField(
            model_name='field',
            name='page',
            field=models.ForeignKey(blank=True, help_text='NULL → глобальное поле', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates.page'),
        ),
        migrations.AddField(
            model_name='field',
            name='template',
            field=models.ForeignKey(help_text='Шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates.template'),
        ),
        migrations.AddField(
            model_name='asset',
            name='page',
            field=models.ForeignKey(blank=True, help_text='NULL → глобальный ассет', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='templates.page'),
        ),
        migrations.AddField(
            model_name='asset',
            name='template',
            field=models.ForeignKey(help_text='Шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='templates.template'),
        ),
        migrations.AlterUniqueTogether(
            name='templatepermission',
            unique_together={('template', 'grantee')},
        ),
        migrations.AlterUniqueTogether(
            name='pagesettings',
            unique_together={('page', 'format_setting')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('template', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='formatsetting',
            unique_together={('format', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('template', 'page', 'key')},
        ),
    ]
