# Generated by Django 4.2.8 on 2025-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('template', 'page', 'key')},
        ),
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(help_text='Порядок отображения поля'),
        ),
    ]
